// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enableEmbedding": boolean;
      "isMultimodal": boolean;
      "llmApiKey": string;
      "llmBaseUrl": string;
      "llmModelName": string;
      "llmTemperature": number;
      "embeddingApiKey": string;
      "embeddingBaseUrl": string;
      "embeddingModelName": string;
    };
  }
}
